### ISSUE TITLE
Possible bug in example_LJ_model.F90

### ISSUE THREAD

**Issue by erlendd** [libAtoms/pymatnest#1]
I think there's a bug in the pymatnest fortran example model: example_LJ_model.f90. 

In ll_eval_energy there is a term:
`
if (i==j) E_term = E_term * 0.5
`
It looks like this is to prevent double-counting, however I think the double-counting actually happens then the indices i and j are different (not the same, as would be implied by the if(i==j) line above).

For example if I've got two atoms then the i and j loops give me:
i=0, j=0
i=0, j=1
i=1, j=0
i=1, j=1

As far as I can see the only potential for a double-count of the energy in the i == j cases is when the 0th images are considered (i.e. dj1, dj2, dj3 all equal 0) and that is correctly prevented by the line:
`
if (i == j .and. dj1 == 0 .and. dj2 == 0 .and. dj3 == 0) cycle
`
The double-counting actually happens for the two cases (i=0, j=1) and (i=1, j=0) when the 0th image of each is being computed.

I.e. in the two-atom case given above there is a double-count between:
 i=0, j=1 and dj1 = dj2 = dj3 = 0
and
 i=1, j=0 and dj1 = dj2 = dj3 = 0

Apologies if there's a mistake in my logic here.

**Comment by albapa** [comment]
>
> For example if I've got two atoms then the i and j loops give me:
> i=0, j=0
> i=0, j=1
> i=1, j=0
> i=1, j=1
>
> I think this is prevented by the loop construction
   do i=1, N
   do j=i, N

Albert

**Comment by noambernstein** [comment]
Also, the ( (i == j .and. dj1 == 0 .and. dj2 == 0 .and. dj3 == 0) is not
removing double counting, but (divergent) self interaction.

Anyway, the reason is subtle, but I'm pretty sure that it's in fact
correct.  You can prove it to yourself (empirically) in a couple of ways.
One is to call the model for two unit cells, one a primitive cell, and one
a supercell, so that some i-i interactions across cells become i-j
interactions within a cell, and see that the energy per atom is the same.
The other is to look at a simple diagram, like the one I attached. Solid
lines are interactions that count fully, dashed are 0.5 (i == j).  Note
that, as Albert pointed out, the loop is i=1,N, j=i,N, so no pairs that
have j < i.

**Comment by erlendd** [comment]
Thanks for the replies. I agree about the follow part preventing one of the issues I mentioned:
`
do i=1, N
   do j=i, N
`
However I'm still not sure why the 
`
if (i==j) E_term = E_term * 0.5 
`
is done. 

There is a similar block of code in the DFT-D3 example code available from here: http://www.thch.uni-bonn.de/tc/index.php?section=downloads&subsection=getd3&lang=english and it doesn't have the 0.5 factor.

@noambernstein - I can't see your attachment - is it definitely attached here?

**Comment by pastewka** [comment]
Hi Erlend,

A different way to see this is as follows. For pair potentials total energy is

E = 1/2 sum_i sum_j V(r_ij)

If there is a nonzero i==j contribution, that picks up a factor of 1/2.

Lars

________________________________
Von: Erlend Davidson <notifications@github.com>
Gesendet: 20.05.2016 6:56 PM
An: libAtoms/pymatnest
Betreff: Re: [libAtoms/pymatnest] Possible bug in example_LJ_model.F90 (#1) 

Thanks for the replies. I agree about the follow part preventing one of the issues I mentioned:

do i=1, N
do j=i, N

However I'm still not sure why the 

if (i==j) E_term = E_term * 0.5 

is done.

There is a similar block of code in the DFT-D3 example code available from here: http://www.thch.uni-bonn.de/tc/index.php?section=downloads&subsection=getd3&lang=english and it doesn't have the 0.5 factor.

@noambernstein - I can't see your attachment - is it definitely attached here?

**Comment by erlendd** [comment]
@pastewka - ah ok, thanks - that makes sense now!
