### ISSUE TITLE
Nested sampling failed for converge_down_to_T

### ISSUE THREAD

**Issue by pythonpanda2** [libAtoms/pymatnest#10]
[ERROR.tar.gz](https://github.com/libAtoms/pymatnest/files/5129710/ERROR.tar.gz)

 I am running  NS for a GAP model with   '**converge_down_to_T**'  . But the runs failed with an MPI abort. 

For sanity check i took the LJ input file available in the path below and redid the NS.

https://github.com/libAtoms/pymatnest/blob/master/example_inputs/inputs.test.periodic.MD.lammps.converged

The NS input   for LJ   with converge_down_to_T failed with the same error. All the inputs and outputs are attached for your reference. 

I was previously using  **n_iter_times_fraction_killed**  which was working fine and ran for many iterations.

**Comment by noambernstein** [comment]
I'm at a bit of a loss, since the output and error files don't show
anything, but it is intentionally calling MPI_Abort.  If I can reproduce
the issue with the LJ test file, I'll have more info.  Otherwise we'll have
to see if we can convince your parallel running system to turn off
buffering, since that may be causing some of the useful output to be lost.

**Comment by pythonpanda2** [comment]
I tried to change the debug flag to see if i can get more information out. But it did not make much difference for this specific issue. 

Oddly the input works with out any issue if i switch off **converge_down_to_T** and turn on **n_iter_times_fraction_killed**  .

**Comment by noambernstein** [comment]
Can you try a serial run?

**Comment by pythonpanda2** [comment]
There was indeed an issue with MPI shared memory mode and i fixed it. But then it again fails on serial runs

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

**Comment by noambernstein** [comment]
On Wed, Aug 26, 2020 at 1:27 PM pythonpanda2 <notifications@github.com>
wrote:

>
>
> There was indeed an issue with MPI shared memory mode and i fixed it. But
> then it again fails on serial runs
>
>
> application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
>
>
But nothing additional to stout or stderr? What if you don’t use mpirun? It
should function that way, and may give more info.

**Comment by pythonpanda2** [comment]
It does give a lot more of output if i dont use srun.  Please find the output below:

```
0 NS 0 Uncaught Exception Type: <class 'TypeError'>
0 NS 0 Value: '>' not supported between instances of 'float' and 'NoneType'
0 NS 0 Traceback: <traceback object at 0x2b36e01d4730>
Traceback (most recent call last):
  File "/home/gsivaraman/pymatnest/ns_run", line 6, in <module>
    ns_run.main()
  File "/gpfs/fs1/home/gsivaraman/pymatnest/ns_run.py", line 3923, in main
    final_iter = do_ns_loop()
  File "/gpfs/fs1/home/gsivaraman/pymatnest/ns_run.py", line 2323, in do_ns_loop
    log_Z_term_max = max(log_Z_term_max, np.amax(log_a-converge_down_to_beta*Emax))
TypeError: '>' not supported between instances of 'float' and 'NoneType'
0 NS 0 Aborting
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```

**Comment by pythonpanda2** [comment]
Please note that this output is for for the LJ example from the repo.

**Comment by bernstei** [comment]
I'm pretty sure a bug was introduced in a recent change to update the code for python3.  Once I've confirmed this we'll update the github version.

**Comment by pythonpanda2** [comment]
Thank you so much, @bernstei

**Comment by bernstei** [comment]
Please try the github branch 
https://github.com/libAtoms/pymatnest/tree/log_Z_term_max_fix <https://github.com/libAtoms/pymatnest/tree/log_Z_term_max_fix>if that works, let me know.

**Comment by pythonpanda2** [comment]
Thanks a lot for taking your time and acting on the issue. Prima facie, looks like it is working.

But  i will run couple of longer tests and get back to you on this .

**Comment by pythonpanda2** [comment]
The test converged.  Seems to be working. Thanks a lot again.
