### ISSUE TITLE
MPI restart bug?

### ISSUE THREAD

**Issue by casv2** [libAtoms/pymatnest#16]
Restarting Nested Sampling runs by first concatenating the walkers
```
ACE_NS.snapshot.8607.*.extxyz > ACE_NS.snapshot.8607.all.extxyz
```
and specying restart input file:
```
restart_file=ACE_NS.snapshot.8607.all.extxyz
```
has always worked for me, and still seems to run fine running in serial. However, using the most recent pymatnest using MPI I get something weird like this:
```
6 truncating traj file to start_first_iter 8608
 Uncaught Exception Type: <class 'TypeError'>
 Value: '<' not supported between instances of 'NoneType' and 'int'
 Traceback: <traceback object at 0x14775b2d5680>
 Aborting
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6
```
I think it happens during the distributions of walkers over the MPI instances right after reading them in from the restart file. 

This only happens at restarts weirdly enough... And when restarting in serial all looks fine

I'm not sure how this can be related to the latest ASE calculator functionality, judging by the code changes it actually looks unlikely it has got anything to do with it, but I do feel it's related somehow... 

Starting a NS run from scratch using MPI works fine, it's just the MPI restarts raising this error

**Comment by bernstei** [comment]
BTW, I think restarts should work automatically if you do restart_file=AUTO, or something like that, without having to do any concatenation manually.  Let me check the details.

**Comment by casv2** [comment]
Thanks I wasn't aware of this! Very user friendly. It seems specifying `AUTO` creates the same file essentially:
```
ship_test.snapshot.8607.ALL.extxyz
```
Error unfortunately still persists:
```
21051542]], masses=..., momenta=..., calculator=SinglePointCalculator(...)), Atoms(symbols='Mo8Ta8W8Nb8Ti8', pbc=True, cell=[[0.21586761756891532, 1.7578246458371511, -11.37303874314057], [0.8311939903931189, 8.739286250465193, 0.44707764182992626], [7.886863039125518, -1.0594684747029637, 2.875911038111933]], masses=..., momenta=..., calculator=SinglePointCalculator(...))]
6 truncating traj file to start_first_iter 8608
 Uncaught Exception Type: <class 'TypeError'>
 Value: '<' not supported between instances of 'NoneType' and 'int'
 Traceback: <traceback object at 0x14fa94bc4200>
 Aborting
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6
```

**Comment by bernstei** [comment]
Can you pack up the restart file and all the other related files, and put them on dropbox or something?  I’ll also need to know how many cores you are running on. For some reason the traceback has so little info (no line number, e.g.), it’ll be hard to debug without that, although I suppose I can try a restart on another setup, but I suspect it’s probably some edge case.

**Comment by casv2** [comment]
Sure! Let me first try different number of MPI processes, see if that gives us more info

**Comment by casv2** [comment]
Files are here: https://we.tl/t-wBSmlGegfd

I've been running it on 28 cores generally. I just tried with 2 mpi tasks and that managed to get a seemingly different error message?
```
Uncaught Exception Type: <class 'BlockingIOError'>
 Value: [Errno 11] write could not complete without blocking
 Traceback: <traceback object at 0x1551bd85bd80>
 Aborting
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
```

Thanks for having a look!

**Comment by liviabp** [comment]
Can you confirm that this happens with an ASE calculator only? I've just quickly tested it with lammps, and it restarted fine.
I've tried your files, but I must miss something: I've installed ace, but I get the error "module 'ace' has no attribute 'ACECalculator' "?
Also, I guess this is just a mistake, but two traj files are missing from your tar, and that causes a restart to fail.

**Comment by casv2** [comment]
More specifically it only happens when restarting with an ASE calculator and MPI, in serial it's fine. Also anything else looks fine. The missing files I may have deleted after a serial run generated them. I don't think it should matter as the 8607 snapshots are all there and that's were I'd like to continue, but please correct me if I'm wrong.

**Comment by liviabp** [comment]
Missing traj files are a problem (at least an empty file should exist for all processes), but that would stop with an error saying that. 
A few years ago we had a similar issue with MPI restarts, but only on certain machines. Then the ase.io caused the problem, as it wants to be parallel by default, so did not allow replicas to access their own snapshots. I wonder if something similar might be a problem here...

**Comment by casv2** [comment]
Thanks for having a look, I just encoutered the bug again on a different run and only restarted using `restart_file=AUTO` and same error appeared:

```
 Uncaught Exception Type: <class 'TypeError'>
 Value: '<' not supported between instances of 'NoneType' and 'int'
 Traceback: <traceback object at 0x15258aaffa00>
 Aborting
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
```

All files, are here: https://we.tl/t-BbpG8ox3yF

**Comment by bernstei** [comment]
I just run with -np 2 and it appeared to work, at least getting as far as printing the initial enthalpy lines.  I'll try to  run on 28 cores next

**Comment by casv2** [comment]
Could it be my MPI set up then...? Hmm, I've never seen it happen before, thanks for checking it out

**Comment by bernstei** [comment]
I just wasn't patient enough.  It appears to happen when it tries to truncate the existing traj files to the correct length.  

There are two parts to the restart.  One is reading the old configs.  The other is truncating and then appending to the existing traj files.  I'm guessing the problem is in the latter, and it makes sense, if some traj files are missing. 

Why are they missing?  One is empty (12) and two are just not there (25, 27).  I can fix the code so it doesn't crash, but you'll be missing chunks from your trajectory.

**Comment by casv2** [comment]
Have you tried the second link I provided? I didn't touch any of the files there, none of the files should be missing, and the error also pops up.

The first link may have a file missing as I was messing around and trying to debug myself, checking what happened swapping out the serial and MPI. Perhaps best to ignore that zip completely, I must've corrupted it myself. I do think this bug is unrelated to the missing files though.

**Comment by bernstei** [comment]
OK, I'll take a look at that one.

**Comment by bernstei** [comment]
Did you change your julia setup between the 1st and second links?  My `pyjulip` doesn't define `ACE1`.

**Comment by bernstei** [comment]
BTW, We should possibly open a separate issue for restarts with different numbers of MPI tasks.  Whether or not that's the problem here, the trajectory truncation will probably be pretty broken if you try it.

**Comment by casv2** [comment]
I did not, I forgot to set `ASE_calc_module=ACE_pyjulip` to `ASE_calc_module=ACE_interfaces` for you. I think you must have had that installed.

**Comment by bernstei** [comment]
Yes, it's working when I go back to ACE_interfaces.  And I do reproduce your problem with the OK trajectory files, so I'm investigating further.

**Comment by casv2** [comment]
Thanks a lot!

**Comment by bernstei** [comment]
OK - the problem really does have to do with truncating the old traj files.  I'm not sure what's going on yet, but the traj file for process 3 is the one that's causing problems.

**Comment by bernstei** [comment]
Aha - process 3's traj file has only 1 configuration, and it's from after the snapshot, so it needs to be truncated to an empty file, and I didn't think of that when I coded up the truncation.  I think I have a fix - if it works, I'll mention this issue when I create the PR.
