### ISSUE TITLE
ns_process_traj: quippy dependencies and python 2 code

### ISSUE THREAD

**Issue by casv2** [libAtoms/pymatnest#18]
`ns_process_traj` has some old quippy dependencies, python 2 print statements and it seems also some indentation issues currently.  We need this I think in order to look at XRD or perhaps short order parameters.

**Comment by bernstei** [comment]
I probably have a fix floating around.  There's a discussion of a complete rewrite, so I don't want to put too much more effort into it, but minimal stuff is probably worth it.
