### ISSUE TITLE
'cell' variable isn't being set since recent updates

### ISSUE THREAD

**Issue by erlendd** [libAtoms/pymatnest#3]
In Fortran models the 'cell' variable isn't being passed correctly to ll_eval_energy(...). In my own tests it's either all zeros, or all zeros except for the last value. My model works in previous versions of the pymatnest code (e.g. from around May-June), and I normally set cell using max_volume_per_atom keyword.

Has there been a change in functionality, or is this a bug?

**Comment by noambernstein** [comment]
I've been using it a lot with no problems. Are you using the latest master? Can you either send an input file that demonstrates the problem and/or regress your version enough to figure out what's the last version that worked for you?

  Noam

**Comment by erlendd** [comment]
Hi Noam, thanks for the response.

Yes I did a git pull just yesterday.

Here's the input file I'm using, it's for a GAP-type model that I wrote.
Basically with the ll_eval_energy function/subroutine in my Fortran model, if I print out 'cell' just after variable declarations it's all zeros. 

`
# starting volume (in this example it is Angstrom^3)
max_volume_per_atom=638.277381
# 1 atoms with atomic number 1 and mass 1.0
start_species=1 1 1.0
start_energy_ceiling=50

converge_down_to_T=10
# size of live set
n_walkers=256
# at each iteration 1 walker is killed
n_cull=1
# total number of iterations will be n_iter_per_walker*n_walkers
##n_iter_per_walker=100
# prefix of all the output files
out_file_prefix=output.MD.fortran

# use MC generating a new walker
atom_algorithm=MD
n_model_calls_expected=3      
n_atom_steps=5                
# length of atomic trajectory in each step
atom_traj_len=5               
# number of cell volume steps
n_cell_volume_steps=0         
# number of cell shear steps
n_cell_shear_steps=0          
# number of cell strectch steps
n_cell_stretch_steps=0        

MD_atom_timestep=0.01
MD_atom_timestep_max=1.0  
MD_adjust_max_rate=0.95
MD_adjust_min_rate=0.5

#MC_atom_step_size=0.1
#MC_atom_step_size_max=1.0

FORTRAN_model=HFe_gap_model.so
# use the supplied fortran code
energy_calculator=fortran

rng=numpy
`

**Comment by erlendd** [comment]
Ok, I think I might have found it.

In fortranMCMD.py in the eval_energy(..) method the call to the Fortran library has changed from:
        
`return self.model_lib.ll_eval_energy_(ctypes.byref(n), at.get_positions(), ctypes.byref(n_extra_data_c), extra_data, at.get_cell())`

to

`return self.model_lib.ll_eval_energy_(ctypes.byref(n), at.get_atomic_numbers().astype(np.int32), at.get_positions(), ctypes.byref(n_extra_data_c), extra_data, at.get_cell())`

Which breaks compatibility with my (older) model. I see now that there's a new 'Z' argument in the example Fortran models...

`double precision function ll_eval_energy(N, Z, pos, n_extra_data, extra_data, cell)`

**Comment by noambernstein** [comment]
Wow - I hadn't even thought that far back, before we added support for multi component systems. I guess it's been in my private branch so long, but just made it into master. So it's ok now?

   Noam

**Comment by erlendd** [comment]
Yes, just tested and that was the fix. I'll close this.
Might be an idea to document the change somewhere if it's easy to do, as it doesn't cause a segfault it just gives bad results, which is a little more dangerous.
