### ISSUE TITLE
Incorrect Contents of `misc_calc_lib`

### ISSUE THREAD

**Issue by rosenbrockc** [libAtoms/pymatnest#7]
@MartinSchlegel Following the instructions for the XRD, it appears that `misc_calc_lib` was inadvertently overwritten with the contents of `make_thermal_average_xrd_rdfd_lenhisto`.

```
Traceback (most recent call last):
  File "../pymatnest/make_thermal_average_xrd_rdfd_lenhisto.py", line 1, in <module>
    import misc_calc_lib
  File "/home/ubuntu/pymatnest/misc_calc_lib.py", line 163, in <module>
    rdfd_results = misc_calc_lib.rdfd_QUIP(QUIP_path,at,n_a,r_range)
AttributeError: 'module' object has no attribute 'rdfd_QUIP'
```

This should be a trivial fix. Thanks!

**Comment by MartinSchlegel** [comment]
@rosenbrockc Sorry, yes, that's what happened. I have fixed it. Thanks for the notice!
Let me know how it goes.

**Comment by gabor1** [comment]
can we close this ?
