### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jan-janssen** [libAtoms/pymatnest#8]
Is this project licensed under an opensource license?

**Comment by gabor1** [comment]
I will post a license file imminently.

**Comment by jan-janssen** [comment]
Any update regarding the license?

**Comment by gabor1** [comment]
Thanks for the prod. I’ve now heard from all contributors, and we agreed to put a GPLv3 into the repo. Enjoy.

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/
